# Generated by Django 6.0.7 on 2026-07-20 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(blank=True, default='غير مصنف', max_length=100)),
                ('cost_usd', models.FloatField(default=0)),
                ('price_usd', models.FloatField(default=0)),
                ('stock', models.FloatField(default=0)),
                ('image', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(unique=True)),
                ('date', models.CharField(max_length=10)),
                ('customer', models.CharField(blank=True, default='', max_length=200)),
                ('rate', models.FloatField()),
                ('currency', models.CharField(default='both', max_length=10)),
                ('items_json', models.TextField(default='[]')),
                ('total_usd', models.FloatField(default=0)),
                ('total_lbp', models.FloatField(default=0)),
                ('voided', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['no'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('in', 'دخول'), ('out', 'خروج')], max_length=3)),
                ('qty', models.FloatField()),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('receipt_no', models.CharField(blank=True, default='', max_length=20)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
    ]
